package project2;


public class Analysis {

	public static void main(String[] args)
	{
		int a1k =   1000;
		int a10k =  10000;
		int a100k = 100000;
		int[] random1k = RWArrays.read("R1k.txt",a1k);
		int[] random10k = RWArrays.read("R10k.txt",a10k);
		int[] random100k = RWArrays.read("R100k.txt",a100k);		
		int[] sorted1k = RWArrays.read("S1k.txt",a1k);
		int[] sorted10k = RWArrays.read("S10k.txt",a10k);
		int[] sorted100k = RWArrays.read("S100k.txt",a100k);		
		int[] almostsorted1k = RWArrays.read("AS1k.txt",a1k);
		int[] almostsorted10k = RWArrays.read("AS10k.txt",a10k);
		int[] almostsorted100k = RWArrays.read("AS100k.txt",a100k);
			
//		System.out.println("R 1k" + "    :" + Arrays.toString(random1k));
//		System.out.println("R 10k" + "   :" + Arrays.toString(random10k));
//		System.out.println("R 100k" + "  :" + Arrays.toString(random100k));
//		System.out.println("S 1k" + "    :" + Arrays.toString(sorted1k));
//		System.out.println("S 10k" + "   :" + Arrays.toString(sorted10k));
//		System.out.println("S 100k " + " :" + Arrays.toString(sorted100k));
//		System.out.println("AS 1k" + "   :" + Arrays.toString(almostsorted1k));
//		System.out.println("AS 10k" + "  :" + Arrays.toString(almostsorted10k));
//		System.out.println("AS 100k" + " :" + Arrays.toString(almostsorted100k));

//		System.out.print("SelectionSort Random 1k :");
//		Timecompare.stime(random1k);
//		System.out.print("SelectionSort Random 10k :");
//		Timecompare.stime(random10k);
//		System.out.print("SelectionSort Random 100k :");
//		Timecompare.stime(random100k);	
//		System.out.print("SelectionSort Sorted 1k :");
//		Timecompare.stime(sorted1k);
//		System.out.print("SelectionSort Sorted 10k :");
//		Timecompare.stime(sorted10k);
//		System.out.print("SelectionSort Sorted 100k :");
//		Timecompare.stime(sorted100k);
//		System.out.print("SelectionSort Almost Sorted 1k :");
//		Timecompare.stime(almostsorted1k);
//		System.out.print("SelectionSort Almost Sorted 10k :");
//		Timecompare.stime(almostsorted10k);
//		System.out.print("SelectionSort Almost Sorted 100k :");
//		Timecompare.stime(almostsorted100k);
//		
//		random1k = RWArrays.read("R1k.txt",a1k);
//		random10k = RWArrays.read("R10k.txt",a10k);
//		random100k = RWArrays.read("R100k.txt",a100k);		
//		sorted1k = RWArrays.read("S1k.txt",a1k);
//		sorted10k = RWArrays.read("S10k.txt",a10k);
//		sorted100k = RWArrays.read("S100k.txt",a100k);		
//		almostsorted1k = RWArrays.read("AS1k.txt",a1k);
//		almostsorted10k = RWArrays.read("AS10k.txt",a10k);
//		almostsorted100k = RWArrays.read("AS100k.txt",a100k);
//		System.out.print("\nInsertionSort Random 1k :");
//		Timecompare.itime(random1k);
//		System.out.print("InsertionSort Random 10k :");
//		Timecompare.itime(random10k);
//		System.out.print("InsertionSort Random 100k :");
//		Timecompare.itime(random100k);	
//		System.out.print("InsertionSort Sorted 1k :");
//		Timecompare.itime(sorted1k);
//		System.out.print("InsertionSort Sorted 10k :");
//		Timecompare.itime(sorted10k);
//		System.out.print("InsertionSort Sorted 100k :");
//		Timecompare.itime(sorted100k);
//		System.out.print("InsertionSort Almost Sorted 1k :");
//		Timecompare.itime(almostsorted1k);
//		System.out.print("InsertionSort Almost Sorted 10k :");
//		Timecompare.itime(almostsorted10k);
//		System.out.print("InsertionSort Almost Sorted 100k :");
//		Timecompare.itime(almostsorted100k);
//		
//		random1k = RWArrays.read("R1k.txt",a1k);
//		random10k = RWArrays.read("R10k.txt",a10k);
//		random100k = RWArrays.read("R100k.txt",a100k);		
//		sorted1k = RWArrays.read("S1k.txt",a1k);
//		sorted10k = RWArrays.read("S10k.txt",a10k);
//		sorted100k = RWArrays.read("S100k.txt",a100k);		
//		almostsorted1k = RWArrays.read("AS1k.txt",a1k);
//		almostsorted10k = RWArrays.read("AS10k.txt",a10k);
//		almostsorted100k = RWArrays.read("AS100k.txt",a100k);
//		System.out.print("\nBubbleSort Random 1k :");
//		Timecompare.btime(random1k);
//		System.out.print("BubbleSort Random 10k :");
//		Timecompare.btime(random10k);
//		System.out.print("BubbleSort Random 100k :");
//		Timecompare.btime(random100k);	
//		System.out.print("BubbleSort Sorted 1k :");
//		Timecompare.btime(sorted1k);
//		System.out.print("BubbleSort Sorted 10k :");
//		Timecompare.btime(sorted10k);
//		System.out.print("BubbleSort Sorted 100k :");
//		Timecompare.btime(sorted100k);
//		System.out.print("BubbleSort Almost Sorted 1k :");
//		Timecompare.btime(almostsorted1k);
//		System.out.print("BubbleSort Almost Sorted 10k :");
//		Timecompare.btime(almostsorted10k);
//		System.out.print("BubbleSort Almost Sorted 100k :");
//		Timecompare.btime(almostsorted100k);
//		
//		random1k = RWArrays.read("R1k.txt",a1k);
//		random10k = RWArrays.read("R10k.txt",a10k);
//		random100k = RWArrays.read("R100k.txt",a100k);		
//		sorted1k = RWArrays.read("S1k.txt",a1k);
//		sorted10k = RWArrays.read("S10k.txt",a10k);
//		sorted100k = RWArrays.read("S100k.txt",a100k);		
//		almostsorted1k = RWArrays.read("AS1k.txt",a1k);
//		almostsorted10k = RWArrays.read("AS10k.txt",a10k);
//		almostsorted100k = RWArrays.read("AS100k.txt",a100k);
//		System.out.print("\nBubbleSortCount Random 1k :");
//		Timecompare.bctime(random1k);
//		System.out.print("BubbleSortCount Random 10k :");
//		Timecompare.bctime(random10k);
//		System.out.print("BubbleSortCount Random 100k :");
//		Timecompare.bctime(random100k);	
//		System.out.print("BubbleSortCount Sorted 1k :");
//		Timecompare.bctime(sorted1k);
//		System.out.print("BubbleSortCount Sorted 10k :");
//		Timecompare.bctime(sorted10k);
//		System.out.print("BubbleSortCount Sorted 100k :");
//		Timecompare.bctime(sorted100k);
//		System.out.print("BubbleSortCount Almost Sorted 1k :");
//		Timecompare.bctime(almostsorted1k);
//		System.out.print("BubbleSortCount Almost Sorted 10k :");
//		Timecompare.bctime(almostsorted10k);
//		System.out.print("BubbleSortCount Almost Sorted 100k :");
//		Timecompare.bctime(almostsorted100k);
		
		random1k = RWArrays.read("R1k.txt",a1k);
		random10k = RWArrays.read("R10k.txt",a10k);
		random100k = RWArrays.read("R100k.txt",a100k);		
		sorted1k = RWArrays.read("S1k.txt",a1k);
		sorted10k = RWArrays.read("S10k.txt",a10k);
		sorted100k = RWArrays.read("S100k.txt",a100k);		
		almostsorted1k = RWArrays.read("AS1k.txt",a1k);
		almostsorted10k = RWArrays.read("AS10k.txt",a10k);
		almostsorted100k = RWArrays.read("AS100k.txt",a100k);
		System.out.print("\nQuickSort Random 1k :");
		Timecompare.qtime(random1k, 0, random1k.length-1);
		System.out.print("QuickSort Random 10k :");
		Timecompare.qtime(random10k, 0, random10k.length-1);
		System.out.print("QuickSort Random 100k :");
		Timecompare.qtime(random100k, 0, random100k.length-1);	
		System.out.print("QuickSort Sorted 1k :");
		Timecompare.qtime(sorted1k, 0, sorted1k.length-1);
		System.out.print("QuickSort Sorted 10k :");
		Timecompare.qtime(sorted10k, 0, sorted10k.length-1);
		System.out.print("QuickSort Sorted 100k :");
		Timecompare.qtime(sorted100k, 0, sorted100k.length-1);
		System.out.print("QuickSort Almost Sorted 1k :");
		Timecompare.qtime(almostsorted1k, 0, almostsorted1k.length-1);
		System.out.print("QuickSort Almost Sorted 10k :");
		Timecompare.qtime(almostsorted10k, 0, almostsorted10k.length-1);
		System.out.print("QuickSort Almost Sorted 100k :");
		Timecompare.qtime(almostsorted100k, 0, almostsorted100k.length-1);
		
//		random1k = RWArrays.read("R1k.txt",a1k);
//		random10k = RWArrays.read("R10k.txt",a10k);
//		random100k = RWArrays.read("R100k.txt",a100k);		
//		sorted1k = RWArrays.read("S1k.txt",a1k);
//		sorted10k = RWArrays.read("S10k.txt",a10k);
//		sorted100k = RWArrays.read("S100k.txt",a100k);		
//		almostsorted1k = RWArrays.read("AS1k.txt",a1k);
//		almostsorted10k = RWArrays.read("AS10k.txt",a10k);
//		almostsorted100k = RWArrays.read("AS100k.txt",a100k);
//		System.out.print("\nMergeSort Random 1k :");
//		Timecompare.mtime(random1k, 0, random1k.length-1);
//		System.out.print("MergeSort Random 10k :");
//		Timecompare.mtime(random10k, 0, random10k.length-1);
//		System.out.print("MergeSort Random 100k :");
//		Timecompare.mtime(random100k, 0, random100k.length-1);	
//		System.out.print("MergeSort Sorted 1k :");
//		Timecompare.mtime(sorted1k, 0, sorted1k.length-1);
//		System.out.print("MergeSort Sorted 10k :");
//		Timecompare.mtime(sorted10k, 0, sorted10k.length-1);
//		System.out.print("MergeSort Sorted 100k :");
//		Timecompare.mtime(sorted100k, 0, sorted100k.length-1);
//		System.out.print("MergeSort Almost Sorted 1k :");
//		Timecompare.mtime(almostsorted1k, 0, almostsorted1k.length-1);
//		System.out.print("MergeSort Almost Sorted 10k :");
//		Timecompare.mtime(almostsorted10k, 0, almostsorted10k.length-1);
//		System.out.print("MergeSort Almost Sorted 100k :");
//		Timecompare.mtime(almostsorted100k, 0, almostsorted100k.length-1);
	}
}
